from ForwardIndex import *
from InvertedIndex import create_lexicon

def add_articles(listOfJson):
    path = 'articles_dataset\json\\nela-gt-2021\\newsdata\\test\\'
    f_i = forward_Indexing(path)
    i_index = create_lexicon(f_i)

    fa = open('Barrels\Inverted_indexa.json', 'w')
    fb = open('Barrels\Inverted_indexb.json', 'w')
    fc = open('Barrels\Inverted_indexc.json', 'w')
    fd = open('Barrels\Inverted_indexd.json', 'w')
    fe = open('Barrels\Inverted_indexe.json', 'w')
    ff = open('Barrels\Inverted_indexf.json', 'w')
    fg = open('Barrels\Inverted_indexg.json', 'w')
    fh = open('Barrels\Inverted_indexh.json', 'w')
    fi = open('Barrels\Inverted_indexi.json', 'w')
    fj = open('Barrels\Inverted_indexj.json', 'w')
    fk = open('Barrels\Inverted_indexk.json', 'w')
    fl = open('Barrels\Inverted_indexl.json', 'w')
    fm = open('Barrels\Inverted_indexm.json', 'w')
    fn = open('Barrels\Inverted_indexn.json', 'w')
    fo = open('Barrels\Inverted_indexo.json', 'w')
    fp = open('Barrels\Inverted_indexp.json', 'w')
    fq = open('Barrels\Inverted_indexq.json', 'w')
    fr = open('Barrels\Inverted_indexr.json', 'w')
    fs = open('Barrels\Inverted_indexs.json', 'w')
    ft = open('Barrels\Inverted_indext.json', 'w')
    fu = open('Barrels\Inverted_indexu.json', 'w')
    fv = open('Barrels\Inverted_indexv.json', 'w')
    fw = open('Barrels\Inverted_indexw.json', 'w')
    fx = open('Barrels\Inverted_indexx.json', 'w')
    fy = open('Barrels\Inverted_indexy.json', 'w')
    fz = open('Barrels\Inverted_indexz.json', 'w')
    fother = open('Barrels\Inverted_indexother.json', 'w')

    ii = [json.loads(fa.read())
    ,json.loads(fb.read())
    ,json.loads(fc.read())
    ,json.loads(fd.read())
    ,json.loads(fe.read())
    ,json.loads(ff.read())
    ,json.loads(fg.read())
    ,json.loads(fh.read())
    ,json.loads(fi.read())
    ,json.loads(fj.read())
    ,json.loads(fk.read())
    ,json.loads(fl.read())
    ,json.loads(fm.read())
    ,json.loads(fn.read())
    ,json.loads(fo.read())
    ,json.loads(fp.read())
    ,json.loads(fq.read())
    ,json.loads(fr.read())
    ,json.loads(fs.read())
    ,json.loads(ft.read())
    ,json.loads(fu.read())
    ,json.loads(fv.read())
    ,json.loads(fw.read())
    ,json.loads(fx.read())
    ,json.loads(fy.read())
    ,json.loads(fz.read())
    ,json.loads(fother.read())]

    letters = 'abcdefghijklmnopqrstuvwxyz'
    word_bank = list(i_index.keys())
    for word in word_bank:
        letters.find(word[0])
        